FROM postgres
# COPY pg_hba.conf /var/lib/postgresql/data/
ENV POSTGRES_DB ghe_dev
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD sqlshar3d
ENV POSTGRES_HOST_AUTH_METHOD md5
COPY init.sh /docker-entrypoint-initdb.d/

# apt-get update && apt-get install procps/net-tools
