#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

-- Started on 2023-03-30 18:23:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 228 (class 1255 OID 41116)
-- Name: update_teams_trigger_func(); Type: FUNCTION; Schema: public; Owner: postgres
--

-- Role: ghe_admin
DROP ROLE IF EXISTS ghe_admin;

CREATE ROLE ghe_admin WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  PASSWORD 'sqlshar3d';

-- Role: ghe_user_read_only
DROP ROLE IF EXISTS ghe_user_read_only;

CREATE ROLE ghe_user_read_only WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'sqlshar3d';



--
-- TOC entry 214 (class 1259 OID 24595)
-- Name: circuit_teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.circuit_teams (
    id integer NOT NULL,
    circuit_id integer,
    team_id integer
);


ALTER TABLE public.circuit_teams OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 24594)
-- Name: circuit_teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.circuit_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuit_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 24587)
-- Name: circuits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.circuits (
    id integer NOT NULL,
    name character varying NOT NULL,
    start_date date,
    end_date date,
    managed_by character varying NOT NULL,
    rounds integer,
    total_rounds integer DEFAULT 2 NOT NULL
);


ALTER TABLE public.circuits OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 24586)
-- Name: circuits_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.circuits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circuits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24728)
-- Name: issue_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.issue_types (
    id integer NOT NULL,
    text character varying(150) NOT NULL,
    sub_issue_id integer
);


ALTER TABLE public.issue_types OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24727)
-- Name: issue_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.issue_types ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.issue_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24630)
-- Name: matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches (
    id integer NOT NULL,
    team_1_id integer,
    team_2_id integer,
    team_1_shots integer,
    team_2_shots integer,
    team_1_goals integer,
    team_2_goals integer,
    team_1_saves integer,
    team_2_saves integer,
    winning_team_id integer,
    circuit_id integer,
    round integer,
    next_match_id integer,
    match_number integer,
    state character varying,
    name character varying
);


ALTER TABLE public.matches OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24629)
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 24720)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    issue_type integer NOT NULL,
    message character varying(500),
    user_id integer NOT NULL,
    mod_user_id integer NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24719)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24678)
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    discord_access_token "char" NOT NULL,
    discord_refresh_token "char" NOT NULL
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24702)
-- Name: team_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.team_types (
    id integer NOT NULL,
    name character varying,
    max_players integer
);


ALTER TABLE public.team_types OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24713)
-- Name: team_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.team_types ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.team_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 41085)
-- Name: team_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.team_users (
    id integer NOT NULL,
    team_id integer NOT NULL,
    user_id integer,
    approved boolean DEFAULT false,
    is_sub boolean
);


ALTER TABLE public.team_users OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 41088)
-- Name: team_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.team_users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.team_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24606)
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    id integer NOT NULL,
    name character varying NOT NULL,
    team_lead_id integer,
    total_shots integer DEFAULT 0,
    total_goals integer DEFAULT 0,
    total_saves integer DEFAULT 0,
    total_wins integer DEFAULT 0,
    total_losses integer DEFAULT 0,
    type_id integer DEFAULT 1,
    region character varying(3),
    created_at time without time zone DEFAULT now(),
    last_updated time without time zone DEFAULT now()
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 24605)
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 24577)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying NOT NULL,
    email character varying NOT NULL,
    mod_score integer DEFAULT 0,
    admin boolean DEFAULT false NOT NULL,
    discord_id integer,
    team_id integer,
    platform character varying,
    tracker_link character varying,
    rank character varying,
    tracker_verified boolean DEFAULT false,
    rl_username character varying,
    discord_name character varying,
    notifs integer
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 24585)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3407 (class 0 OID 24595)
-- Dependencies: 214
-- Data for Name: circuit_teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.circuit_teams (id, circuit_id, team_id) FROM stdin;
1	1	1
2	1	2
3	1	3
\.


--
-- TOC entry 3405 (class 0 OID 24587)
-- Dependencies: 212
-- Data for Name: circuits; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.circuits (id, name, start_date, end_date, managed_by, rounds, total_rounds) FROM stdin;
1	The Golden Cup	2022-09-01	2022-10-15	4	\N	2
\.


--
-- TOC entry 3418 (class 0 OID 24728)
-- Dependencies: 225
-- Data for Name: issue_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.issue_types (id, text, sub_issue_id) FROM stdin;
3	Other	\N
1	Unverified Team	\N
\.


--
-- TOC entry 3411 (class 0 OID 24630)
-- Dependencies: 218
-- Data for Name: matches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches (id, team_1_id, team_2_id, team_1_shots, team_2_shots, team_1_goals, team_2_goals, team_1_saves, team_2_saves, winning_team_id, circuit_id, round, next_match_id, match_number, state, name) FROM stdin;
4	\N	\N	\N	\N	\N	\N	\N	\N	\N	1	2	\N	3	\N	Team 1 vs Team 2
1	1	2	\N	\N	\N	\N	\N	\N	\N	1	1	4	1	\N	Team 3 vs Team 4
3	3	4	\N	\N	\N	\N	\N	\N	\N	1	1	4	2	\N	TBA
\.


--
-- TOC entry 3416 (class 0 OID 24720)
-- Dependencies: 223
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, issue_type, message, user_id, mod_user_id) FROM stdin;
\.


--
-- TOC entry 3412 (class 0 OID 24678)
-- Dependencies: 219
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, user_id, discord_access_token, discord_refresh_token) FROM stdin;
\.


--
-- TOC entry 3413 (class 0 OID 24702)
-- Dependencies: 220
-- Data for Name: team_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.team_types (id, name, max_players) FROM stdin;
1	standard	5
2	doubles	3
3	solo	1
\.


--
-- TOC entry 3419 (class 0 OID 41085)
-- Dependencies: 226
-- Data for Name: team_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.team_users (id, team_id, user_id, approved, is_sub) FROM stdin;
1	2	1	f	\N
\.


--
-- TOC entry 3409 (class 0 OID 24606)
-- Dependencies: 216
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams (id, name, team_lead_id, total_shots, total_goals, total_saves, total_wins, total_losses, type_id, region, created_at, last_updated) FROM stdin;
1	team1	1	0	0	0	0	0	1	\N	21:01:00.775539	21:01:17.577785
2	team2	5	0	0	0	0	0	1	\N	21:01:00.775539	21:01:17.577785
3	team3	8	0	0	0	0	0	1	\N	21:01:00.775539	21:01:17.577785
4	team4	11	0	0	0	0	0	1	\N	21:01:00.775539	21:09:13.922425
\.


--
-- TOC entry 3402 (class 0 OID 24577)
-- Dependencies: 209
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, mod_score, admin, discord_id, team_id, platform, tracker_link, rank, tracker_verified, rl_username, discord_name, notifs) FROM stdin;
5	test4	user4@test.com	0	f	\N	2	\N	\N	\N	\N	\N	\N	\N
6	test5	user5@test.com	0	f	\N	2	\N	\N	\N	\N	\N	\N	\N
7	test6	user6@test.com	0	f	\N	2	\N	\N	\N	\N	\N	\N	\N
8	test7	user7@test.com	0	f	\N	3	\N	\N	\N	\N	\N	\N	\N
9	test8	user8@test.com	0	f	\N	3	\N	\N	\N	\N	\N	\N	\N
10	test9	user9@test.com	0	f	\N	3	\N	\N	\N	\N	\N	\N	\N
11	test10	user10@test.com	0	f	\N	4	\N	\N	\N	\N	\N	\N	\N
12	test11	user11@test.com	0	f	\N	4	\N	\N	\N	\N	\N	\N	\N
13	test12	user12@test.com	0	f	\N	4	\N	\N	\N	\N	\N	\N	\N
14	name	name@test.com	0	f	13	\N	\N	\N	\N	\N	\N	\N	\N
15	name	email@email.com	0	f	12	\N	\N	\N	\N	\N	\N	\N	\N
1	test	user@test.com	0	f	\N	1	\N	\N	\N	\N	\N	boop#1234	\N
4	admin_user	kaiasnowfall@gmail.com	0	t	\N	\N	\N	\N	\N	\N	\N	\N	\N
2	test2	user2@test.com	0	f	\N	1	\N	\N	\N	\N	\N	ellie#2000	\N
3	test3	user3@test.com	0	f	\N	1	\N	\N	\N	\N	\N	fyke#4687	\N
\.


--
-- TOC entry 3436 (class 0 OID 0)
-- Dependencies: 213
-- Name: circuit_teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.circuit_teams_id_seq', 3, true);


--
-- TOC entry 3437 (class 0 OID 0)
-- Dependencies: 211
-- Name: circuits_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.circuits_id_seq', 1, true);


--
-- TOC entry 3438 (class 0 OID 0)
-- Dependencies: 224
-- Name: issue_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.issue_types_id_seq', 3, true);


--
-- TOC entry 3439 (class 0 OID 0)
-- Dependencies: 217
-- Name: matches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_id_seq', 4, true);


--
-- TOC entry 3440 (class 0 OID 0)
-- Dependencies: 222
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, false);


--
-- TOC entry 3441 (class 0 OID 0)
-- Dependencies: 221
-- Name: team_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.team_types_id_seq', 1, false);


--
-- TOC entry 3442 (class 0 OID 0)
-- Dependencies: 227
-- Name: team_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.team_users_id_seq', 1, true);


--
-- TOC entry 3443 (class 0 OID 0)
-- Dependencies: 215
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_id_seq', 5, true);


--
-- TOC entry 3444 (class 0 OID 0)
-- Dependencies: 210
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 15, true);


--
-- TOC entry 3229 (class 2606 OID 24599)
-- Name: circuit_teams circuit_teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.circuit_teams
    ADD CONSTRAINT circuit_teams_pkey PRIMARY KEY (id);


--
-- TOC entry 3227 (class 2606 OID 24591)
-- Name: circuits circuits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.circuits
    ADD CONSTRAINT circuits_pkey PRIMARY KEY (id);


--
-- TOC entry 3245 (class 2606 OID 24732)
-- Name: issue_types issue_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.issue_types
    ADD CONSTRAINT issue_types_pkey PRIMARY KEY (id);


--
-- TOC entry 3237 (class 2606 OID 24634)
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);


--
-- TOC entry 3243 (class 2606 OID 24726)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 3239 (class 2606 OID 24682)
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 3241 (class 2606 OID 24706)
-- Name: team_types team_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_types
    ADD CONSTRAINT team_types_pkey PRIMARY KEY (id);


--
-- TOC entry 3248 (class 2606 OID 41095)
-- Name: team_users team_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_users
    ADD CONSTRAINT team_users_pkey PRIMARY KEY (id);


--
-- TOC entry 3235 (class 2606 OID 24610)
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- TOC entry 3225 (class 2606 OID 24584)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3230 (class 1259 OID 49326)
-- Name: fki_circuit_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_circuit_id_fk ON public.circuit_teams USING btree (circuit_id);


--
-- TOC entry 3231 (class 1259 OID 49332)
-- Name: fki_team_id_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_team_id_fk ON public.circuit_teams USING btree (team_id);


--
-- TOC entry 3223 (class 1259 OID 32898)
-- Name: fki_team_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_team_id_fkey ON public.users USING btree (team_id);


--
-- TOC entry 3232 (class 1259 OID 32919)
-- Name: fki_team_lead_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_team_lead_fk ON public.teams USING btree (team_lead_id);


--
-- TOC entry 3233 (class 1259 OID 32940)
-- Name: fki_team_type_fk; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_team_type_fk ON public.teams USING btree (type_id);


--
-- TOC entry 3246 (class 1259 OID 49320)
-- Name: fki_user_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_user_id_fkey ON public.team_users USING btree (user_id);


--
-- TOC entry 3262 (class 2620 OID 41117)
-- Name: teams update_teams_trigger; Type: TRIGGER; Schema: public; Owner: postgres
--



--
-- TOC entry 3256 (class 2606 OID 24645)
-- Name: matches circuit_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT circuit_id_fk FOREIGN KEY (circuit_id) REFERENCES public.circuits(id) NOT VALID;


--
-- TOC entry 3250 (class 2606 OID 49321)
-- Name: circuit_teams circuit_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.circuit_teams
    ADD CONSTRAINT circuit_id_fk FOREIGN KEY (circuit_id) REFERENCES public.circuits(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3258 (class 2606 OID 24660)
-- Name: matches original_match_1_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT original_match_1_id_fk FOREIGN KEY (next_match_id) REFERENCES public.matches(id) NOT VALID;


--
-- TOC entry 3254 (class 2606 OID 24635)
-- Name: matches team_1_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT team_1_id_fk FOREIGN KEY (team_1_id) REFERENCES public.teams(id) NOT VALID;


--
-- TOC entry 3255 (class 2606 OID 24640)
-- Name: matches team_2_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT team_2_id_fk FOREIGN KEY (team_2_id) REFERENCES public.teams(id) NOT VALID;


--
-- TOC entry 3251 (class 2606 OID 49327)
-- Name: circuit_teams team_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.circuit_teams
    ADD CONSTRAINT team_id_fk FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3249 (class 2606 OID 32925)
-- Name: users team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 3260 (class 2606 OID 49310)
-- Name: team_users team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_users
    ADD CONSTRAINT team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3252 (class 2606 OID 32930)
-- Name: teams team_lead_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT team_lead_fk FOREIGN KEY (team_lead_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 3253 (class 2606 OID 32935)
-- Name: teams team_type_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT team_type_fk FOREIGN KEY (type_id) REFERENCES public.team_types(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;


--
-- TOC entry 3259 (class 2606 OID 24683)
-- Name: sessions user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3261 (class 2606 OID 49315)
-- Name: team_users user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.team_users
    ADD CONSTRAINT user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED NOT VALID;


--
-- TOC entry 3257 (class 2606 OID 24650)
-- Name: matches winning_team_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT winning_team_id_fk FOREIGN KEY (winning_team_id) REFERENCES public.teams(id) NOT VALID;


--
-- TOC entry 3426 (class 0 OID 0)
-- Dependencies: 214
-- Name: TABLE circuit_teams; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.circuit_teams TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.circuit_teams TO ghe_admin;


--
-- TOC entry 3427 (class 0 OID 0)
-- Dependencies: 212
-- Name: TABLE circuits; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.circuits TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.circuits TO ghe_admin;


--
-- TOC entry 3428 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE issue_types; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.issue_types TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.issue_types TO ghe_admin;


--
-- TOC entry 3429 (class 0 OID 0)
-- Dependencies: 218
-- Name: TABLE matches; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.matches TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.matches TO ghe_admin;


--
-- TOC entry 3430 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE notifications; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.notifications TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.notifications TO ghe_admin;


--
-- TOC entry 3431 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE sessions; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.sessions TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.sessions TO ghe_admin;


--
-- TOC entry 3432 (class 0 OID 0)
-- Dependencies: 220
-- Name: TABLE team_types; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.team_types TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.team_types TO ghe_admin;


--
-- TOC entry 3433 (class 0 OID 0)
-- Dependencies: 226
-- Name: TABLE team_users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.team_users TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.team_users TO ghe_admin;


--
-- TOC entry 3434 (class 0 OID 0)
-- Dependencies: 216
-- Name: TABLE teams; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.teams TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.teams TO ghe_admin;


--
-- TOC entry 3435 (class 0 OID 0)
-- Dependencies: 209
-- Name: TABLE users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.users TO ghe_user_read_only WITH GRANT OPTION;
GRANT ALL ON TABLE public.users TO ghe_admin;


--
-- TOC entry 2070 (class 826 OID 16418)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON TABLES  TO ghe_user_read_only WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES  TO ghe_admin;


-- Completed on 2023-03-30 18:23:02

--
-- PostgreSQL database dump complete
--




EOSQL